// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20251220203552_InvoiceDetailWeight")]
    partial class InvoiceDetailWeight
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Business", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Direccion");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("Ciudad");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreado");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Documento");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.Property<string>("Province")
                        .HasColumnType("text")
                        .HasColumnName("Provincia");

                    b.Property<string>("SriEnvironment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("AmbienteSri");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaActualizado");

                    b.HasKey("Id");

                    b.ToTable("Empresa", (string)null);
                });

            modelBuilder.Entity("Core.Entities.BusinessCertificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer")
                        .HasColumnName("EmpresaId");

                    b.Property<string>("CertificateBase64")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CertificadoBase64");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CertificadoClave");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId")
                        .IsUnique();

                    b.ToTable("CertificadoEmpresa", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Direccion");

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer")
                        .HasColumnName("EmpresaId");

                    b.Property<string>("Cellphone")
                        .HasColumnType("text")
                        .HasColumnName("Celular");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreado");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Documento");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TipoDocumento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Correo");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.Property<string>("Telephone")
                        .HasColumnType("text")
                        .HasColumnName("Telefono");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaActualizado");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("Core.Entities.EmissionPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Codigo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreado");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Descripcion");

                    b.Property<int>("EstablishmentId")
                        .HasColumnType("integer")
                        .HasColumnName("EstablecimientoId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaActualizado");

                    b.HasKey("Id");

                    b.HasIndex("EstablishmentId");

                    b.ToTable("PuntoEmision", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Establishment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer")
                        .HasColumnName("EmpresaId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Codigo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreado");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaActualizado");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("Establecimiento", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ClaveAcceso");

                    b.Property<string>("AdditionalInformation")
                        .HasColumnType("text")
                        .HasColumnName("InformacionAdicional");

                    b.Property<DateTime?>("AuthorizationDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("FechaAutorizacion");

                    b.Property<string>("AuthorizationNumber")
                        .HasColumnType("text")
                        .HasColumnName("NumeroAutorizacion");

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer")
                        .HasColumnName("EmpresaId");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("ClienteId");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("Descripcion");

                    b.Property<decimal>("DiscountTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("TotalDescuento");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("FechaVencimiento");

                    b.Property<int>("EmissionPointId")
                        .HasColumnType("integer")
                        .HasColumnName("PuntoEmisionId");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Ambiente");

                    b.Property<int>("EstablishmentId")
                        .HasColumnType("integer")
                        .HasColumnName("EstablecimientoId");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("FechaFactura");

                    b.Property<bool>("IsElectronic")
                        .HasColumnType("boolean")
                        .HasColumnName("Electronico");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("MetodoPago");

                    b.Property<int>("PaymentTermDays")
                        .HasColumnType("integer")
                        .HasColumnName("DiasPago");

                    b.Property<string>("ReceiptType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TipoRecibo");

                    b.Property<string>("Sequential")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Secuencial");

                    b.Property<string>("SriMessage")
                        .HasColumnType("text")
                        .HasColumnName("MensajeSri");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Estado");

                    b.Property<decimal>("SubtotalWithTaxes")
                        .HasColumnType("numeric")
                        .HasColumnName("Subtotal");

                    b.Property<decimal>("SubtotalWithoutTaxes")
                        .HasColumnType("numeric")
                        .HasColumnName("SubtotalBase");

                    b.Property<decimal>("TaxTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("TotalImpuesto");

                    b.Property<decimal>("TotalInvoice")
                        .HasColumnType("numeric")
                        .HasColumnName("Total");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("UsuarioId");

                    b.Property<string>("XmlSigned")
                        .HasColumnType("text")
                        .HasColumnName("XmlFirmado");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmissionPointId");

                    b.HasIndex("EstablishmentId");

                    b.HasIndex("UserId");

                    b.ToTable("Factura", (string)null);
                });

            modelBuilder.Entity("Core.Entities.InvoiceDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric")
                        .HasColumnName("Descuento");

                    b.Property<decimal>("GrossWeight")
                        .HasColumnType("numeric")
                        .HasColumnName("PesoBruto");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("integer")
                        .HasColumnName("FacturaId");

                    b.Property<decimal>("NetWeight")
                        .HasColumnType("numeric")
                        .HasColumnName("PesoNeto");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("ProductoId");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("Cantidad");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric")
                        .HasColumnName("Subtotal");

                    b.Property<int>("TaxId")
                        .HasColumnType("integer")
                        .HasColumnName("ImpuestoId");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("numeric")
                        .HasColumnName("TasaImpuesto");

                    b.Property<decimal>("TaxValue")
                        .HasColumnType("numeric")
                        .HasColumnName("ValorImpuesto");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("Total");

                    b.Property<int>("UnitMeasureId")
                        .HasColumnType("integer")
                        .HasColumnName("UnidadMedidaId");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("PrecioUnitario");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("BodegaId");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ProductId");

                    b.HasIndex("TaxId");

                    b.HasIndex("UnitMeasureId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("FacturaDetalle", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Kardex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer")
                        .HasColumnName("EmpresaId");

                    b.Property<DateTime>("MovementDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("FechaMovimiento");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TipoMovimiento");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("ProductoId");

                    b.Property<decimal>("QuantityIn")
                        .HasColumnType("numeric")
                        .HasColumnName("CantidadEntrada");

                    b.Property<decimal>("QuantityOut")
                        .HasColumnType("numeric")
                        .HasColumnName("CantidadSalida");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Referencia");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("numeric")
                        .HasColumnName("CostoTotal");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("numeric")
                        .HasColumnName("CostoUnitario");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("BodegaId");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Kardex", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer")
                        .HasColumnName("EmpresaId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Descripcion");

                    b.Property<decimal>("GrossWeight")
                        .HasColumnType("numeric")
                        .HasColumnName("PesoBruto");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<bool>("Iva")
                        .HasColumnType("boolean")
                        .HasColumnName("ConIva");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.Property<decimal>("NetWeight")
                        .HasColumnType("numeric")
                        .HasColumnName("PesoNeto");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("Precio");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Sku");

                    b.Property<int>("TaxId")
                        .HasColumnType("integer")
                        .HasColumnName("ImpuestoId");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Tipo");

                    b.Property<int>("UnitMeasureId")
                        .HasColumnType("integer")
                        .HasColumnName("UnidadMedidaId");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("TaxId");

                    b.HasIndex("UnitMeasureId");

                    b.ToTable("Producto", (string)null);
                });

            modelBuilder.Entity("Core.Entities.ProductWarehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("MaxStock")
                        .HasColumnType("numeric")
                        .HasColumnName("CantidadMaxima");

                    b.Property<decimal>("MinStock")
                        .HasColumnType("numeric")
                        .HasColumnName("CantidadMinima");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("ProductoId");

                    b.Property<decimal>("Stock")
                        .HasColumnType("numeric")
                        .HasColumnName("Cantidad");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("BodegaId");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("ProductoBodega", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer")
                        .HasColumnName("EmpresaId");

                    b.Property<decimal>("DiscountTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("TotalDescuento");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NumeroDocumento");

                    b.Property<int>("EmissionPointId")
                        .HasColumnType("integer")
                        .HasColumnName("PuntoEmisionId");

                    b.Property<int>("EstablishmentId")
                        .HasColumnType("integer")
                        .HasColumnName("EstablecimientoId");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("FechaCompra");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Referencia");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Estado");

                    b.Property<decimal>("SubtotalWithTaxes")
                        .HasColumnType("numeric")
                        .HasColumnName("Subtotal");

                    b.Property<decimal>("SubtotalWithoutTaxes")
                        .HasColumnType("numeric")
                        .HasColumnName("SubtotalBase");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer")
                        .HasColumnName("ProveedorId");

                    b.Property<decimal>("TaxTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("TotalImpuesto");

                    b.Property<decimal>("TotalPurchase")
                        .HasColumnType("numeric")
                        .HasColumnName("Total");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("EmissionPointId");

                    b.HasIndex("EstablishmentId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Compra", (string)null);
                });

            modelBuilder.Entity("Core.Entities.PurchaseDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric")
                        .HasColumnName("Descuento");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("ProductoId");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("integer")
                        .HasColumnName("CompraId");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("Cantidad");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric")
                        .HasColumnName("Subtotal");

                    b.Property<int>("TaxId")
                        .HasColumnType("integer")
                        .HasColumnName("ImpuestoId");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("numeric")
                        .HasColumnName("TasaImpuesto");

                    b.Property<decimal>("TaxValue")
                        .HasColumnType("numeric")
                        .HasColumnName("ValorImpuesto");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("Total");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("numeric")
                        .HasColumnName("CostoUnitario");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("BodegaId");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseId");

                    b.HasIndex("TaxId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("CompraDetalle", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Direccion");

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer")
                        .HasColumnName("EmpresaId");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("RazonSocial");

                    b.Property<string>("Cellphone")
                        .HasColumnType("text")
                        .HasColumnName("Celular");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreado");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Documento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Correo");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<string>("Telephone")
                        .HasColumnType("text")
                        .HasColumnName("Telefono");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaActualizado");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("Proveedor", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Tax", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer")
                        .HasColumnName("EmpresaId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Codigo");

                    b.Property<string>("CodePercentage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CodigoPorcentaje");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Grupo");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric")
                        .HasColumnName("Tasa");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("Impuesto", (string)null);
                });

            modelBuilder.Entity("Core.Entities.UnitMeasure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer")
                        .HasColumnName("EmpresaId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Codigo");

                    b.Property<decimal>("FactorBase")
                        .HasColumnType("numeric")
                        .HasColumnName("FactorBase");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("UnidadMedida", (string)null);
                });

            modelBuilder.Entity("Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("Direccion");

                    b.Property<string>("Cellphone")
                        .HasColumnType("text")
                        .HasColumnName("Celular");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text")
                        .HasColumnName("RazonSocial");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreado");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Documento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Correo");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NombreCompleto");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("ImagenUrl");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("Clave");

                    b.Property<string>("Sequence")
                        .HasColumnType("text")
                        .HasColumnName("Secuencia");

                    b.Property<string>("Telephone")
                        .HasColumnType("text")
                        .HasColumnName("Telefono");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaActualizado");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NombreUsuario");

                    b.HasKey("Id");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Core.Entities.UserBusiness", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer")
                        .HasColumnName("EmpresaId");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("UserId");

                    b.ToTable("UsuarioEmpresa", (string)null);
                });

            modelBuilder.Entity("Core.Entities.UserEmissionPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmissionPointId")
                        .HasColumnType("integer")
                        .HasColumnName("PuntoEmisionId");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("EmissionPointId");

                    b.HasIndex("UserId");

                    b.ToTable("UsuarioPuntoEmision", (string)null);
                });

            modelBuilder.Entity("Core.Entities.UserEstablishment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EstablishmentId")
                        .HasColumnType("integer")
                        .HasColumnName("EstablecimientoId");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("EstablishmentId");

                    b.HasIndex("UserId");

                    b.ToTable("UsuarioEstablecimiento", (string)null);
                });

            modelBuilder.Entity("Core.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("RolId");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UsuarioRol", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Direccion");

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer")
                        .HasColumnName("EmpresaId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Codigo");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean")
                        .HasColumnName("Principal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("Bodega", (string)null);
                });

            modelBuilder.Entity("Core.Entities.BusinessCertificate", b =>
                {
                    b.HasOne("Core.Entities.Business", "Business")
                        .WithOne("BusinessCertificate")
                        .HasForeignKey("Core.Entities.BusinessCertificate", "BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Core.Entities.Customer", b =>
                {
                    b.HasOne("Core.Entities.Business", "Business")
                        .WithMany("Customers")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Core.Entities.EmissionPoint", b =>
                {
                    b.HasOne("Core.Entities.Establishment", "Establishment")
                        .WithMany("EmissionPoints")
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Establishment");
                });

            modelBuilder.Entity("Core.Entities.Establishment", b =>
                {
                    b.HasOne("Core.Entities.Business", "Business")
                        .WithMany("Establishments")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Core.Entities.Invoice", b =>
                {
                    b.HasOne("Core.Entities.Business", "Business")
                        .WithMany("Invoices")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.EmissionPoint", "EmissionPoint")
                        .WithMany("Invoices")
                        .HasForeignKey("EmissionPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Establishment", "Establishment")
                        .WithMany("Invoices")
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.User", "User")
                        .WithMany("Invoices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("Customer");

                    b.Navigation("EmissionPoint");

                    b.Navigation("Establishment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.InvoiceDetail", b =>
                {
                    b.HasOne("Core.Entities.Invoice", "Invoice")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Product", "Product")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Tax", "Tax")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("TaxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.UnitMeasure", "UnitMeasure")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("UnitMeasureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Warehouse", "Warehouse")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Product");

                    b.Navigation("Tax");

                    b.Navigation("UnitMeasure");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Core.Entities.Kardex", b =>
                {
                    b.HasOne("Core.Entities.Business", "Business")
                        .WithMany("Kardexes")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Product", "Product")
                        .WithMany("Kardexes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Warehouse", "Warehouse")
                        .WithMany("Kardexes")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Core.Entities.Product", b =>
                {
                    b.HasOne("Core.Entities.Business", "Business")
                        .WithMany("Products")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Tax", "Tax")
                        .WithMany("Products")
                        .HasForeignKey("TaxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.UnitMeasure", "UnitMeasure")
                        .WithMany("Products")
                        .HasForeignKey("UnitMeasureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("Tax");

                    b.Navigation("UnitMeasure");
                });

            modelBuilder.Entity("Core.Entities.ProductWarehouse", b =>
                {
                    b.HasOne("Core.Entities.Product", "Product")
                        .WithMany("ProductWarehouses")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Warehouse", "Warehouse")
                        .WithMany("ProductWarehouses")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Core.Entities.Purchase", b =>
                {
                    b.HasOne("Core.Entities.Business", "Business")
                        .WithMany("Purchases")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.EmissionPoint", "EmissionPoint")
                        .WithMany()
                        .HasForeignKey("EmissionPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Establishment", "Establishment")
                        .WithMany("Purchases")
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Supplier", "Supplier")
                        .WithMany("Purchases")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("EmissionPoint");

                    b.Navigation("Establishment");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Core.Entities.PurchaseDetail", b =>
                {
                    b.HasOne("Core.Entities.Product", "Product")
                        .WithMany("PurchaseDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Purchase", "Purchase")
                        .WithMany("PurchaseDetails")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Tax", "Tax")
                        .WithMany("PurchaseDetails")
                        .HasForeignKey("TaxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Warehouse", "Warehouse")
                        .WithMany("PurchaseDetails")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Purchase");

                    b.Navigation("Tax");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Core.Entities.Supplier", b =>
                {
                    b.HasOne("Core.Entities.Business", "Business")
                        .WithMany("Suppliers")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Core.Entities.Tax", b =>
                {
                    b.HasOne("Core.Entities.Business", "Business")
                        .WithMany("Taxes")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Core.Entities.UnitMeasure", b =>
                {
                    b.HasOne("Core.Entities.Business", "Business")
                        .WithMany("UnitMeasures")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Core.Entities.UserBusiness", b =>
                {
                    b.HasOne("Core.Entities.Business", "Business")
                        .WithMany("UserBusiness")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.User", "User")
                        .WithMany("UserBusiness")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.UserEmissionPoint", b =>
                {
                    b.HasOne("Core.Entities.EmissionPoint", "EmissionPoint")
                        .WithMany("UserEmissionPoints")
                        .HasForeignKey("EmissionPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.User", "User")
                        .WithMany("UserEmissionPoint")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmissionPoint");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.UserEstablishment", b =>
                {
                    b.HasOne("Core.Entities.Establishment", "Establishment")
                        .WithMany("UserEstablishments")
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.User", "User")
                        .WithMany("UserEstablishment")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Establishment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.UserRole", b =>
                {
                    b.HasOne("Core.Entities.Role", "Role")
                        .WithMany("UserRole")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.User", "User")
                        .WithMany("UserRole")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.Warehouse", b =>
                {
                    b.HasOne("Core.Entities.Business", "Business")
                        .WithMany("Warehouses")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Core.Entities.Business", b =>
                {
                    b.Navigation("BusinessCertificate");

                    b.Navigation("Customers");

                    b.Navigation("Establishments");

                    b.Navigation("Invoices");

                    b.Navigation("Kardexes");

                    b.Navigation("Products");

                    b.Navigation("Purchases");

                    b.Navigation("Suppliers");

                    b.Navigation("Taxes");

                    b.Navigation("UnitMeasures");

                    b.Navigation("UserBusiness");

                    b.Navigation("Warehouses");
                });

            modelBuilder.Entity("Core.Entities.Customer", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("Core.Entities.EmissionPoint", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("UserEmissionPoints");
                });

            modelBuilder.Entity("Core.Entities.Establishment", b =>
                {
                    b.Navigation("EmissionPoints");

                    b.Navigation("Invoices");

                    b.Navigation("Purchases");

                    b.Navigation("UserEstablishments");
                });

            modelBuilder.Entity("Core.Entities.Invoice", b =>
                {
                    b.Navigation("InvoiceDetails");
                });

            modelBuilder.Entity("Core.Entities.Product", b =>
                {
                    b.Navigation("InvoiceDetails");

                    b.Navigation("Kardexes");

                    b.Navigation("ProductWarehouses");

                    b.Navigation("PurchaseDetails");
                });

            modelBuilder.Entity("Core.Entities.Purchase", b =>
                {
                    b.Navigation("PurchaseDetails");
                });

            modelBuilder.Entity("Core.Entities.Role", b =>
                {
                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("Core.Entities.Supplier", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("Core.Entities.Tax", b =>
                {
                    b.Navigation("InvoiceDetails");

                    b.Navigation("Products");

                    b.Navigation("PurchaseDetails");
                });

            modelBuilder.Entity("Core.Entities.UnitMeasure", b =>
                {
                    b.Navigation("InvoiceDetails");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Core.Entities.User", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("UserBusiness");

                    b.Navigation("UserEmissionPoint");

                    b.Navigation("UserEstablishment");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("Core.Entities.Warehouse", b =>
                {
                    b.Navigation("InvoiceDetails");

                    b.Navigation("Kardexes");

                    b.Navigation("ProductWarehouses");

                    b.Navigation("PurchaseDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
